[package]
name = "lifeline"
version = "0.2.0"
description = "Lifeline is a dependency injection library for message-based applications."
keywords = ["async", "tokio", "async", "actor", "actors"]
categories = ["Asynchronous", "Rust patterns"]
authors = ["Austin Jones <implAustin@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project = "0.4.23"
futures = "0.3"
uuid = { version = "0.8", features = ["serde", "v4"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
lru = { version = "0.6.0", optional = true }

async-trait = "0.1"
thiserror = "1.0"
anyhow = "1.0"
impls = "1"
dyn-clone = "1.0"
traitcast = "0.5"
downcast-rs = "1.2.0"

log = "0.4"
regex = "1.3"


tokio = { version = "0.2", features = ["stream", "sync", "rt-core"] }

[dev-dependencies]
anyhow = "1.0"
simple_logger = "1.6"
tokio = { version = "0.2", features = ["stream", "sync", "time", "macros", "rt-threaded"] }

[features]
default = ["serialize"]
serialize = ["uuid", "serde", "lru"]
# [features]
# default = ["tokio-executor"]
# tokio-executor = ["tokio"]