[package]
name = "lifeline"
version = "0.3.1"
description = "Lifeline is a dependency injection library for message-based applications."
keywords = ["async", "tokio", "async", "actor", "actors"]
categories = ["Asynchronous", "Rust patterns"]
readme = "README.md"
authors = ["Austin Jones <implAustin@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
pin-project = "0.4.23"
futures-util = { version = "0.3", default-features = false }

async-trait = "0.1"
thiserror = "1.0"
anyhow = "1.0"

log = "0.4"
regex = "1.3"

tokio = { version = "0.2", default-features = false, optional = true }
async-std = { version = "1.6", default-features = false, optional = true }

[dev-dependencies]
anyhow = "1.0"
simple_logger = "1.9"
tokio = { version = "0.2", features = ["stream", "sync", "time", "macros", "rt-threaded"] }
async-std = { version = "1.6", features = ["attributes", "unstable"] }

[features]
default = ["dyn-bus", "tokio-executor", "tokio-channels"]

dyn-bus = []

tokio-executor = ["tokio/rt-core"]
tokio-channels = ["tokio/stream", "tokio/sync"]

async-std-executor = ["async-std/default"]
async-std-channels = ["async-std/unstable"]

[[example]]
name = "async-std"
required-features = ["dyn-bus", "async-std-executor", "async-std-channels"]